// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3TZmDhXfcu6TP3uu2GhI5FZ551WrnGFA',
    appId: '1:119153274000:web:c2317da0c151edcf597c15',
    messagingSenderId: '119153274000',
    projectId: 'connect-app-amitsing',
    authDomain: 'connect-app-amitsing.firebaseapp.com',
    storageBucket: 'connect-app-amitsing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCN_v9Yop0GmSSiERCgq5uXs0nmoQQ0c',
    appId: '1:119153274000:android:e8fdef627cc914a8597c15',
    messagingSenderId: '119153274000',
    projectId: 'connect-app-amitsing',
    storageBucket: 'connect-app-amitsing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfQCctXaGhcAEHgSX5ZNacd71hH3Raskc',
    appId: '1:119153274000:ios:231edf711561eba0597c15',
    messagingSenderId: '119153274000',
    projectId: 'connect-app-amitsing',
    storageBucket: 'connect-app-amitsing.firebasestorage.app',
    iosBundleId: 'com.example.connectapp',
  );
}
