// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1d8eY381vrMBYAvkrshow-hDA2WCcaZc',
    appId: '1:1089526595697:web:fd7f17a7bad29af05e9bd0',
    messagingSenderId: '1089526595697',
    projectId: 'connect-735d9',
    authDomain: 'connect-735d9.firebaseapp.com',
    storageBucket: 'connect-735d9.firebasestorage.app',
    measurementId: 'G-0JL4RJM2JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5cmkgbvrRAnow8KlvGGzLYBgRwVPG3Y',
    appId: '1:1089526595697:android:6c2edd0b9f37abf75e9bd0',
    messagingSenderId: '1089526595697',
    projectId: 'connect-735d9',
    storageBucket: 'connect-735d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6KMH5Bhf83LOuwAxjmfXBOgNfIaYTyI8',
    appId: '1:1089526595697:ios:272e829ebbac89cb5e9bd0',
    messagingSenderId: '1089526595697',
    projectId: 'connect-735d9',
    storageBucket: 'connect-735d9.firebasestorage.app',
    iosBundleId: 'com.example.connectapp',
  );

}